language: node_js

sudo: required
dist: xenial

cache: yarn

addons:
    apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable
          - google-chrome-beta

node_js:
    - "10"

notifications:
    slack:
        secure: kRgRM578pLw6wwt1e7NScR7HPec832XqSkgQM55swVmJYoonF1qUgCl42Qwk52xEZFphWvgp3N0g+tjtzQkNhhe9kEWOQEH0Q3AUC5MYoHEVesyUQFPE7ZXhG6g9qIPFyZriEmQyPyhOKh/UWAjgwjwdLMqPcXwDT4l7X+vJNCeCB8XXPLBhjQnOO5lAI95Q/higBAAZJOHdMLjBCvtmBxo8MTYQgc92j5z42PLprkJ/9YqP1EcynWYxWbHZ/QPNgYHnBNsmWJir/3Ffy897sis/ye6NIcvSwo2OLB+62REbgP0qUyg0XPJ0dmt5/TR72sDsl3BOOavaDKu9oZ5q1oYC7JYXEKMm80OU8lZ6OgaHC/zvMuPjn0WXhCz3SEJnMCc9LsEgu/e2MeMAxSSv0G3FzpADsMNqPgln6z+R5XVqfpYQbjzmdLexqqF/f8fXaUkX7xMB75QIVnoq+9LggeuH8vGKMRhJNLcHErkOvM5Alv5ooHJ49KCwDg+zJpbvu74JHPUiG1HKRXLnND7iV5nKoxsWPTC0dfr8RX5aRxAGmz0/0w/n9SK7i2cQZatHsfvn/MDO9/kuRRjv2QihUrEynpAAxfNlc6gD7IYoq3ORXObBLBbbOIYhwHpYojt3aeAnla3OUXHO/q1ZCQ9ctXW6ozsUKJKRwi1FcXa7StQ=
    email: false

before_install:
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3CB3BD13
    - sudo apt-get update --allow-unauthenticated
    - sudo apt-get install -y --allow-unauthenticated libappindicator1 fonts-liberation
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - sudo dpkg -i google-chrome*.deb

before_script:
    # Clean up detritus left by npm modules that include '.git' directories
    # (like LESS)
    - rm -rf ./node_modules/*/.git/
    # Capture node version
    # - v=$(node --version)
    # Remove broken npm location and link 'good' npm location to it.
    # - p=$(which npm)
    # - rm $p
    # - ln -s /home/travis/.nvm/versions/node/$v/bin/npm $p || true
    # Link TIBET into npm global lib
    - yarn link
    # Build TIBET so that packages are available.
    - tibet build
    - cd ..
    # Build and initialize test project called 'travis'.
    # IMPORTANT: There may be tests that switch on or off based on this project
    # name. Keep them in sync if this is changed!
    - tibet clone travis
    - cd travis
    - tibet init --link
    - tibet lint
    # Repair npm path after 'tibet init' due to npm bug with linked modules
    # - ln -s /home/travis/.nvm/versions/node/$v/bin/npm $p || true
    # Install Karma bits
    - yarn global add karma-cli
    - yarn add karma --dev
    - yarn add karma-chrome-launcher --dev
    - yarn add karma-tibet --dev
    # Relink TIBET after 'npm install' due to npm bug with linked modules
    # (again...)
    - yarn link tibet
    # Configure Karma
    # NOTE These value will load and test the entire TIBET framework. More
    # appropriate values for testing a TIBET application *only* are:
    # - tibet config karma.boot.profile="main@developer"
    # - tibet config karma.boot.script=":test --context='app'"
    - tibet config karma.boot.profile="main@contributor"
    - tibet config karma.script=":test --context='all'"
    - tibet config sherpa.enabled=false

    # Configure Headless Chrome
    - export CHROME_BIN=/usr/bin/google-chrome
    - export DISPLAY=:99.0

    # Make sure to sleep for 3 seconds to give Chrome a chance to start under
    # xvfb
    - sleep 3

services:
    - xvfb

script:
    - karma start --debug
