language: node_js

sudo: required
dist: xenial

addons:
    apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable
          - google-chrome-beta

node_js:
    - "8"

notifications:
    slack:
        secure: kRgRM578pLw6wwt1e7NScR7HPec832XqSkgQM55swVmJYoonF1qUgCl42Qwk52xEZFphWvgp3N0g+tjtzQkNhhe9kEWOQEH0Q3AUC5MYoHEVesyUQFPE7ZXhG6g9qIPFyZriEmQyPyhOKh/UWAjgwjwdLMqPcXwDT4l7X+vJNCeCB8XXPLBhjQnOO5lAI95Q/higBAAZJOHdMLjBCvtmBxo8MTYQgc92j5z42PLprkJ/9YqP1EcynWYxWbHZ/QPNgYHnBNsmWJir/3Ffy897sis/ye6NIcvSwo2OLB+62REbgP0qUyg0XPJ0dmt5/TR72sDsl3BOOavaDKu9oZ5q1oYC7JYXEKMm80OU8lZ6OgaHC/zvMuPjn0WXhCz3SEJnMCc9LsEgu/e2MeMAxSSv0G3FzpADsMNqPgln6z+R5XVqfpYQbjzmdLexqqF/f8fXaUkX7xMB75QIVnoq+9LggeuH8vGKMRhJNLcHErkOvM5Alv5ooHJ49KCwDg+zJpbvu74JHPUiG1HKRXLnND7iV5nKoxsWPTC0dfr8RX5aRxAGmz0/0w/n9SK7i2cQZatHsfvn/MDO9/kuRRjv2QihUrEynpAAxfNlc6gD7IYoq3ORXObBLBbbOIYhwHpYojt3aeAnla3OUXHO/q1ZCQ9ctXW6ozsUKJKRwi1FcXa7StQ=
    email: false

before_install:
    - sudo apt-get update
    - sudo apt-get install -y libappindicator1 fonts-liberation
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - sudo dpkg -i google-chrome*.deb
    - npm install npm@3.10 -g
    - npm cache clean --force

before_script:

    - npm link .
    - tibet build
    - cd ..
    - tibet clone travis
    - cd travis
    - tibet init --link
    - tibet lint
    - npm install -g karma-cli
    - npm install --save-dev karma
    - npm install --save-dev karma-chrome-launcher
    - npm install --save-dev karma-tibet
    - tibet config karma.boot.profile="main@contributor"
    - tibet config karma.script=":test --context='all'"
    - tibet config sherpa.enabled=false

    - export CHROME_BIN=/usr/bin/google-chrome
    - export DISPLAY=:99.0

    # Make sure to sleep for 3 seconds to give Chrome a chance to start under
    # xvfb
    - sleep 3

services:
    - xvfb

script:
    - karma start --debug
