# THIS DOCKERFILE IS USED FOR CONTINUOUS INTEGRATION AND DEPLOYMENT TESTING.

# Start with Node 10.X and the Debian Linux 'Stretch Slim' image.
FROM node:10.16.0-stretch-slim

# Grab the latest package definitions for apt-get
RUN apt-get update

# Add git because some of TIBET's npm packages come from TPI forks of Git
# packages on Github (force 'yes' or otherwise Docker can't complete building
# the package).
RUN apt-get -y install git-core

# Add the prerequisites for Puppeteer.
RUN apt-get update \
     # Install latest chrome dev package, which installs the necessary libs to
     # make the bundled version of Chromium that Puppeteer installs work.
     && apt-get install -y wget --no-install-recommends \
     && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
     && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
     && apt-get update \
     && apt-get install -y google-chrome-unstable --no-install-recommends \
     && rm -rf /var/lib/apt/lists/* \
     && wget --quiet https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /usr/sbin/wait-for-it.sh \
     && chmod +x /usr/sbin/wait-for-it.sh

# Add the non-root 'tester' user.
RUN useradd -ms /bin/bash tester

# cd into the 'tester' user's home directory.
WORKDIR /home/tester

# Copy in the contents of TIBET from the local source directory into the
# Docker image's app directory. By specifying the '--chown' flag, we ensure that
# everything gets the proper permissions.
COPY --chown=node:node . .

# Relink TIBET so that everything that needs to be installed and linked is
# indeed linked.
RUN npm link

# Make sure to build the hook file so that it's available to the CI system.
RUN tibet build_hook

# Make sure to build the loader so that it's available to the CI system.
RUN tibet build_loader

# Switch to the non-root 'tester' user.
USER tester

# Set an entrypoint to bash and we're ready to go!
ENTRYPOINT /usr/local/bin/tibet test
