//  ========================================================================
/*
NAME:   TP.sig.UserIOResponse.js
AUTH:   Scott Shattuck (ss)
NOTE:   Copyright (C) 1999-2009 Technical Pursuit Inc., All Rights
        Reserved. Patent Pending, Technical Pursuit Inc.

        Unless explicitly acquired and licensed under the Technical
        Pursuit License ("TPL") Version 1.5, the contents of this file
        are subject to the Reciprocal Public License ("RPL") Version 1.5
        and You may not copy or use this file in either source code or
        executable form, except in compliance with the terms and
        conditions of the RPL.

        You may obtain a copy of both the TPL and RPL (the "Licenses")
        from Technical Pursuit Inc. at http://www.technicalpursuit.com.

        All software distributed under the Licenses is provided strictly
        on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER
        EXPRESS OR IMPLIED, AND TECHNICAL PURSUIT INC. HEREBY DISCLAIMS
        ALL SUCH WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY
        WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
        QUIET ENJOYMENT, OR NON-INFRINGEMENT. See Licenses for specific
        language governing rights and limitations under the Licenses.
*/
//  ========================================================================

/**
 * @type {TP.sig.UserIOResponse}
 * @synopsis A type used as the common response type for TP.sig.UserIORequests.
 */

//  ------------------------------------------------------------------------

TP.sig.IOResponse.defineSubtype('UserIOResponse');

TP.sig.UserIOResponse.addTraitsFrom(TP.sig.UserIOSignal);

TP.sig.UserIOResponse.Type.resolveTraits(
        TP.ac('shouldLog', 'getSignalName'),
        TP.sig.UserIOResponse);

TP.sig.UserIOResponse.Inst.resolveTraits(
        TP.ac('asSource', 'asDumpString', 'asHTMLString', 'asJSONSource',
                'asPrettyString', 'asXMLString', 'asString', 'at', 'atPut',
                'getSignalName', 'getProperty', 'copy', 'shouldLog', 'init',
                'isRecyclable', 'recycle'),
        TP.sig.UserIOResponse);

//  ========================================================================
//  TP.sig.UserOutput
//  ========================================================================

/**
 * @type {TP.sig.UserOutput}
 * @synopsis A common type for holding output generated by the user.
 */

//  ------------------------------------------------------------------------

TP.sig.UserIOResponse.defineSubtype('UserOutput');

//  ========================================================================
//  TP.sig.UserInput
//  ========================================================================

/**
 * @type {TP.sig.UserInput}
 * @synopsis The type used to contain input from the user. This is the primary
 *     form of TP.sig.UserIOResponse used by the console.
 */

//  ------------------------------------------------------------------------

TP.sig.UserIOResponse.defineSubtype('UserInput');

//  ========================================================================
//  TP.sig.UserInputEntry
//  ========================================================================

/**
 * @type {TP.sig.UserInputEntry}
 * @synopsis A response containing a single entry of user input in what will
 *     likely be a series of query/response pairs. This type is used by the
 *     TP.sig.UserInputSeries request type as its response type.
 */

//  ------------------------------------------------------------------------

TP.sig.UserInput.defineSubtype('UserInputEntry');

//  ------------------------------------------------------------------------
//  end
//  ========================================================================

