.TH "TIBETLAMA\-SAMPLE" "1" "September 2020" "" ""
.SH "NAME"
\fBtibetlama-sample\fR \- short, single\-sentence description
.SH SYNOPSIS
.P
\fBtibetlama\-sample\fP [<optional>\|\.\.\.] <flags>
.SH DESCRIPTION
.P
A normal paragraph\. This can span multiple lines and is terminated with two
or more line endings just like Markdown\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fB\-\-help\fP :
Displays help information\.
.IP \(bu 2
\fB\-\-version\fP :
Displays version information\.

.RE
.SH EXAMPLES
.P
Indent examples with 4 spaces\.
.P
.RS 2
.nf
$ ls
$ ls \-la
.fi
.RE
.SH STANDARDS
.SH SECURITY
.SH SEE ALSO
.P
also(1)

