.TH "NAME" "1" "December 2015" "" ""
.SH "NAME"
\fBname\fR \- short, single\-sentence description
.SH SYNOPSIS
.P
\fBname\fP [<optional>\|\.\.\.] <flags>
.SH DESCRIPTION
.P
A normal paragraph\. This can span multiple lines and is terminated with two
or more line endings just like Markdown\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fB\-h\fP, \fB\-\-help\fP :
Displays the help screen\.
.IP \(bu 2
\fB\-\-version\fP :
Displays version information\.

.RE
.SH SYNTAX
.SH ENVIRONMENT
.SH RETURN VALUES
.SH EXAMPLES
.P
Indent examples with 4 spaces\.
.P
.RS 2
.nf
$ ls
$ ls \-la
.fi
.RE
.SH STANDARDS
.SH SECURITY CONSIDERATIONS
.SH BUGS
.SH HISTORY
.SH AUTHOR
.SH COPYRIGHT
.P
\fBPROJECTNAME\fR is copyright (c) 2015, Rico Sta\. Cruz\. Released under the MIT
license\.
.SH SEE ALSO
.P
ronn\-format(7), ronn(1)

