.TH "TIBET\-VERSION" "1" "August 2016" "" ""
.SH "NAME"
\fBtibet-version\fR \- displays the current project and TIBET version
.SH SYNOPSIS
.P
tibet version [\-\-check]
.SH SYNOPSIS
.P
Displays the current version of TIBET\. Also available as the
.br
\-\-version flag on the 'tibet' command (tibet \-\-version)\.
.P
Use \-\-check to request this command to check whether a newer
.br
version of TIBET has been published\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fB\-\-check\fP :
.br
Tell TIBET to check the current project TIBET version against the latest
.br
released version\. The URL used is whatever value is found in
.br
\fBpath\.lib_version_file\fP\|\.

.RE
.SH EXAMPLES
.SS Display the current application and TIBET version data
.P
.RS 2
.nf
$ tibet version

hello 0\.1\.0 running on TIBET v5\.0\.0\-dev\.7
.fi
.RE
.SS Check on whether there's a newer release of TIBET available
.P
.RS 2
.nf
$ tibet version \-\-check

Your current version v5\.0\.0\-dev\.7 is the latest\.
.fi
.RE
.P
If a new version is available you'll see something similar to:
.P
.RS 2
.nf
Version v5\.0\.0\-dev\.11 is available\. You have v5\.0\.0\-dev\.7
.fi
.RE
.SS View the current mapping for the TIBET latest\-release file
.P
.RS 2
.nf
$ tibet config path\.lib_version_file

http://www\.technicalpursuit\.com/tibet/latest\.js
.fi
.RE
.SH SEE ALSO
.RS 0
.IP \(bu 2
config(1)

.RE

