.TH "TIBET\-START" "1" "October 2017" "" ""
.SH "NAME"
\fBtibet-start\fR \- starts the project's TIBET Data Server
.SH SYNOPSIS
.P
tibet start [<options>] [\-\-env <name>]
.SH DESCRIPTION
.P
Performs project\-specific start operations\. For a TDS\-based project this command
will attempt to start the TDS\. For an Electron project this command will launch
your application's root page in Electron\. For other project types this command
will typically call the current operating system's \fBopen\fP command with your
project's root file\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fB\-\-env\fP :
Specify an environment value to control the server\. This value is used by
the system when loading values from \fBtds\.json\fP, the server's config file\. Common
values are \fBdevelopment\fP (the default), and \fBproduction\fP\|\.
.IP \(bu 2
\fB\-\-tds\.port\fP :
A commonly used \fBtibet config\fP option value which alters the port number the
server should start on\.

.RE
.SH EXAMPLES
.SS Start the server on a default port (1407)
.P
.RS 2
.nf
$ tibet start

                                  ,`
                            __,~//`
   ,///,_            \.~////////'`
  '///////,       //////''`
         '//,   ///'`
            '/_/'
              `
    ////////////////////     ///////////////////  ////
    `//'````````````///      `//'```````````````  '''
     /`              //       /'
    /                //      '/
   ,/____             /'    ,/_____
  /////////;;,,_      //   ,//////////;,_
              `'/,_   '/              `'///,_
                 `'/,_ /                   '//,
                    '/,/,                    '/_
                      `/,                     `/,
                        '                      `/
                                               '/
                                                /

info: hello 0\.1\.0 (development) running on TIBET v5\.0\.0\-dev\.7 at http://127\.0\.0\.1:1407
.fi
.RE
.SS Start the server on a custom port
.P
.RS 2
.nf
$ tibet start \-\-tds\.port 2222

\|\.\.\.
info: test1 0\.1\.0 (development) running on TIBET v5\.0\.0\-dev\.7 at http://127\.0\.0\.1:2222
.fi
.RE
.SS Start the server with a different environment
.P
.RS 2
.nf
$ tibet start \-\-env testing

\|\.\.\.
info: hello 0\.1\.0 (testing) running on TIBET v5\.0\.0\-dev\.7 at http://127\.0\.0\.1:1407
.fi
.RE
.SH SEE ALSO
.RS 0
.IP \(bu 2
tibet\-config(1)

.RE

