.TH "TIBET\-STRIP" "1" "April 2020" "" ""
.SH "NAME"
\fBtibet-strip\fR \- produce a stripped application package
.SH SYNOPSIS
.P
\fBtibet strip [<args>]\fP
.SH DESCRIPTION
.P
This command is experimental and should not be used at the present time\.
.SH OPTIONS
.P
No command options or flags are checked by this command\.
.SH CONFIGURATION SETTINGS
.P
No TIBET configuration variables are utilized by this command\.
.SH ENVIRONMENT VARIABLES
.P
No process environment variables are required by this command\.
.SH EXAMPLES
.SH TIBET SHELL
.P
This command has no client\-side TSH peer command\.
.SH TROUBLESHOOTING
.SH SEE ALSO

