.TH "TIBET\-TAG" "1" "January 2016" "" ""
.SH "NAME"
\fBtibet-tag\fR \- creates a new TIBET tag type
.SH SYNOPSIS
.P
.RS 2
.nf
tibet tag <tagName> [options]
.fi
.RE
.SH DESCRIPTION
.P
Creates a new TIBET tag using the supplied tag name and parameters\.
.P
Tag names can supply one, two or three parts, separated by \fB\|\.\fP or
.br
\fB:\fP\|\. If three parts are supplied, they are used as the root namespace,
.br
the tag type namespace and the tag name, respectively\. If two parts are
.br
supplied, they are used for the tag type namespace and the tag name and
.br
the root namespace is defaulted to either \fBAPP\fP or \fBTP\fP, depending
.br
on whether this command is being executed in an application project or
.br
the TIBET library\. If one part is supplied, and this command is being
.br
executed in an application project, the tag type namespace is defaulted
.br
to the application project name and the root namespace is defaulted as
.br
it is when two parts are supplied\. It is not a valid operation to execute
.br
this command with one part when executed inside of the TIBET library\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fB\-\-package\fP :
.br
Used to determine the cfg package file that will be updated with entries to
.br
load the new tag type and configure it\. If this parameter is not supplied, the
.br
default for a tag being created in a project is \fB~app_cfg/\.xml\fP\|\. For
.br
a tag created in the TIBET library it's \fBlib_cfg/lib_namespaces\.xml\fP\|\.
.IP \(bu 2
\fB\-\-config\fP :
.br
Used as the name of the config package in the cfg package file that the
.br
new tag will be made a part of\. If this parameter is not supplied, the default
.br
for a tag being created in a project is \fBapp_img\fP and for a tag being created
.br
in the TIBET library is the same as the tag namespace name\.
.IP \(bu 2
\fB\-\-dir\fP :
.br
Used as the destination directory for the newly created source code files
.br
representing the tag\. If this parameter is not supplied, the default for a tag
.br
being created in a project is \fB~app_src/tags\fP and for a tag being created in
.br
the TIBET library is \fB~lib_src/\fP\|\.
.IP \(bu 2
\fB\-\-compiled\fP :
.br
Used to determine whether to create a templated tag or a compiled tag\. A
.br
templated tag uses an external template (by default an \.xhtml file) to render
.br
itself into an application, whereas a compiled tag overrides the \fBtagCompile\fP
.br
and manually manipulates the browser's DOM\. The default for this flag is false\.
.IP \(bu 2
\fB\-\-template\fP :
.br
Used to configure the system's \fBcfg\fP parameter that points to this tag
.br
type's template\. If this parameter is not supplied, this defaults to null as, if
.br
the tag is a templated (i\.e\. not compiled) one, the system will automatically
.br
associate a similarly\-named \.xhtml file with the tag's template (this parameter
.br
is not used for compiled tags at all)\. It will assume that this file is in the
.br
same directory as the tag's source \.js file\. Supply a value here if the template
.br
file you wish to use for the tag is in a different directory, is of a different
.br
name or is of a different type (i\.e\. a \.svg file)\. This is highly recommended to
.br
use a virtual URI here (i\.e\. a URI with a leading \fB~\fP)\.
.IP \(bu 2
\fB\-\-style\fP :
.br
Used to determine the style sheet configuration for the tag\. By default each
.br
tag gets a specific style sheet in the same directory with tag type and optional
.br
template\. If you want no style associated you can use the special value
.br
NO_RESULT\. Supply a value here if the tag you are defining has CSS or LESS
.br
style associated with it\. This is highly recommended to use a virtual URI here
.br
(i\.e\. a URI with a leading \fB~\fP)\.

.RE

