.TH "TIBET\-TEST" "1" "May 2019" "" ""
.SH "NAME"
\fBtibet-test\fR \- runs unit/functional tests on your application
.SH SYNOPSIS
.P
tibet test [<target>] [\-\-suite <filter>] [\-\-cases <filter>] [\-\-karma] [\-\-context <app|lib|all>]
.SH DESCRIPTION
.P
Runs unit, functional, and/or integration tests on your application\.
.P
If the \fB\-\-karma\fP flag is true, \fBtibet test\fP checks to see if the \fBkarma\-tibet\fP
testing module and \fBkarma\fP have been installed in your project\. If so the
command delegates to \fBkarma start\fP to run your tests\.
.P
If \fBkarma\fP isn't installed or the \fB\-\-karma\fP flag is false (the default)
tests will run in the context of headless chrome if found\.
.P
In both cases (karma or headless) you can specify a particular test target
object or test suite to run as the first argument to the command\. If you need to
specify both a target and suite use \fB\-\-target\fP and \fB\-\-suite\fP respectively\.
.P
You can limit testing to a particular case or set of cases by using the
\fB\-\-cases\fP parameter\. Both \fB\-\-suite\fP and \fB\-\-cases\fP accept either a string or a
regular expression in JavaScript syntax such as \fB\-\-cases /foo/i\fP\|\.
.P
For headless testing output is to the terminal in colorized TAP format by
default\. Future versions will support additional test output formatters\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fBtarget\fP :
An optional target, usually a type name, to run tests on\. Unlike other test
frameworks, TIBET's tests are typically associated with an object such as a
type\. This lets you quickly test a type by simply specifying it as a \fBtarget\fP\|\.
.IP \(bu 2
\fB\-\-cases\fP :
A specific case name or a /pattern/ to match to filter case names\.
.IP \(bu 2
\fB\-\-context\fP :
Sets the context of the scan which is run\. The default is \fBapp\fP
which scans only application\-level resources, ignoring any potential library
resources\. Other values are \fBlib\fP and \fBall\fP\|\.
.IP \(bu 2
\fB\-\-karma\fP :
Turns on/off the search for a \fBkarma\fP binary and \fBkarma\.conf\.js\fP file\. Using
\fB\-\-no\-karma\fP will force TIBET's basic headless test execution\. The
default value is false\.
.IP \(bu 2
\fB\-\-suite\fP :
A specific suite name or a /pattern/ to match to filter suite names\.

.RE
.SH EXAMPLES
.SS Run default application tests via karma
.P
Assuming you've followed the installation instructions for \fBkarma\-tibet\fP (https:// you can run your karma tests via \fBtibet test\fP:
.P
.RS 2
.nf
$ tibet test \-\-karma

30 06 2016 17:32:46\.557:INFO [karma]: Karma v1\.1\.0 server started at http://0\.0\.0\.0:9876/
30 06 2016 17:32:46\.560:INFO [launcher]: Launching browser Chrome with unlimited concurrency
30 06 2016 17:32:46\.567:INFO [launcher]: Starting browser Chrome
30 06 2016 17:32:48\.803:INFO [Chrome 51\.0\.2704 (Mac OS X 10\.11\.5)]: Connected on socket /#i8jwIIkTNAvAF27lAAAA with id 70331982
Chrome 51\.0\.2704 (Mac OS X 10\.11\.5): Executed 3 of 3 SUCCESS (0\.169 secs / 0 secs)
.fi
.RE
.SS Run default application tests via Headless Chrome
.P
If you haven't installed \fBkarma\fP you can run tests via the \fBtibet test\fP command:
.P
.RS 2
.nf
$ tibet test

# Loading TIBET at 2018\-08\-23T13:32:03\.632Z
# TIBET loaded and active in 6736ms
# TIBET starting test run
# 2 suite(s) found\.
1\.\.3
#
# tibet test APP \-\-suite 'APP suite'
ok \- Has a namespace\.
ok \- Has an application type\.
# pass: 2 total, 2 pass, 0 fail, 0 error, 0 skip, 0 todo, 0 only\.
#
# tibet test APP\.d2d\.app \-\-suite 'APP\.d2d:app suite'
ok \- Is a templated tag\.
# pass: 1 total, 1 pass, 0 fail, 0 error, 0 skip, 0 todo, 0 only\.
#
# PASS: 3 total, 3 pass, 0 fail, 0 error, 0 skip, 0 todo, 0 only\.

# Finished in 2385 ms w/TSH exec time of 93 ms\.
.fi
.RE
.P
NOTE that each test is prefixed with a comment of the form \fB# tibet test \.\.\fP
which allows you to run that specific test suite\.
.SS Force default application tests via headless in a karma\-enabled project
.P
.RS 2
.nf
$ tibet test \-\-no\-karma

# Loading TIBET at 2018\-08\-23T13:32:03\.632Z
# TIBET loaded and active in 6736ms
# TIBET starting test run
# 2 suite(s) found\.
1\.\.3
#
# tibet test APP \-\-suite 'APP suite'
ok \- Has a namespace\.
ok \- Has an application type\.
# pass: 2 total, 2 pass, 0 fail, 0 error, 0 skip, 0 todo, 0 only\.
#
# tibet test APP\.d2d\.app \-\-suite 'APP\.d2d:app suite'
ok \- Is a templated tag\.
# pass: 1 total, 1 pass, 0 fail, 0 error, 0 skip, 0 todo, 0 only\.
#
# PASS: 3 total, 3 pass, 0 fail, 0 error, 0 skip, 0 todo, 0 only\.

# Finished in 2385 ms w/TSH exec time of 93 ms\.
.fi
.RE
.SS Run tests on a specific type
.P
.RS 2
.nf
$ tibet test \-\-karma APP\.hello\.app

overriding karma\.script with: :test  \-target='APP\.hello\.app'
01 07 2016 13:56:55\.444:INFO [karma]: Karma v1\.1\.0 server started at http://0\.0\.0\.0:9876/
01 07 2016 13:56:55\.446:INFO [launcher]: Launching browser Chrome with unlimited concurrency
01 07 2016 13:56:55\.453:INFO [launcher]: Starting browser Chrome
01 07 2016 13:56:56\.838:INFO [Chrome 51\.0\.2704 (Mac OS X 10\.11\.5)]: Connected on socket /#CuLMZuXGzQV1Z_rjAAAA with id 78791384
Chrome 51\.0\.2704 (Mac OS X 10\.11\.5): Executed 1 of 1 SUCCESS (0\.131 secs / 0 secs)
.fi
.RE
.SS Run a specific test suite
.P
.RS 2
.nf
$ tibet test \-\-suite 'APP suite' \-\-no\-karma

# Loading TIBET at 2018\-08\-23T13:32:03\.632Z
# TIBET loaded and active in 6736ms
# TIBET starting test run
# 1 suite(s) found\.
1\.\.2
#
# tibet test APP \-\-suite='APP suite'
ok \- Has a namespace\.
ok \- Has an application type\.
# pass: 2 total, 2 pass, 0 fail, 0 error, 0 skip, 0 todo, 0 only\.
#
# PASS: 2 total, 2 pass, 0 fail, 0 error, 0 skip, 0 todo, 0 only\.

# Finished in 2819 ms w/TSH exec time of 80 ms\.
.fi
.RE

