.TH "TIBET\-HELP" "1" "December 2015" "" ""
.SH "NAME"
\fBtibet-help\fR \- displays help specific to TIBET
.SH SYNOPSIS
.P
.RS 2
.nf
tibet help
tibet help <topic>
tibet <command> \-\-help
.fi
.RE
.SH DESCRIPTION
.P
Displays help for a specific command or the 'tibet' command\.
.P
You can alternatively get usage data via the \fB\-\-usage\fP flag on each command
.br
or complete help output by using the \fB\-\-help\fP flag on the target command\.

