.TH "TIBET\-DEPLOY" "1" "July 2020" "" ""
.SH "NAME"
\fBtibet-deploy\fR \- deploys an application
.SH SYNOPSIS
.P
\fBtibet deploy <helper> [<options>]\fP
.SH DESCRIPTION
.P
Deploys the current application by leveraging a deploy 'helper' or any
available \fBtibet make deploy\fP target\. You can build your own deploy
helper(s) and place them in your application's \fB~app_cmd/deploy\fP directory
for use by this command\.
.P
There are several pre\-built deploy helpers in \fB~lib_cmd/deploy\fP including:
    awselasticbeanstalk
    azurewebapps
    dockerhub
    shipit
.P
Each helper is free to process any additional command line arguments and flags
in whatever fashion makes the most sense given the deployment target\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fBoptions\fP :
An open\-ended set of arguments and flags\. Any content on the command line
can be accessed from within your \fBdeploy\fP helper or make target\.

.RE
.SH CONFIGURATION SETTINGS
.P
No TIBET configuration variables are utilized by this command\.
.SH ENVIRONMENT VARIABLES
.P
No process environment variables are required by this command\.
.SH EXAMPLES
.SS Using Shipit for deployments
.P
.RS 2
.nf
To make use of Shipit for your deployment logic first do three things:

1 Install the `shipit` executable via `npm install \-\-save\-dev shipit`\.
2 Install the shipit `deploy` task via `npm install \-\-save\-dev shipit\-deploy`\.
3 Create a `shipitfile\.js` file containing your specific deployment tasks\.

To run a `shipit`\-based deployment via the `tibet deploy` command
.fi
.RE
.P
enter \fBtibet deploy shipit <environment>\fP along with any options you require\.
.SS Using \fBtibet make deploy\fP for deployments
.P
.RS 2
.nf
To use a `tibet make` target you need to edit the `_deploy` task in your
.fi
.RE
.P
project's \fB~app_cmd/make\fP directory\. The default version of this file simply
outputs a message regarding concrete deployment logic\.
.P
.RS 2
.nf
Deploying via your `makefile\.js`\-based `deploy` target is as simple as
.fi
.RE
.P
entering \fBtibet deploy make\fP once you've updated your make target file to
contain your deployment logic\.
.SH TIBET SHELL
.P
This command has no client\-side TSH peer command\.
.SH TROUBLESHOOTING
.SH SEE ALSO
.RS 0
.IP \(bu 2
tibet\-make(1)

.RE

