.TH "TIBET\-APROPOS" "1" "October 2019" "" ""
.SH "NAME"
\fBtibet-apropos\fR \- list objects/methods related to one or more terms
.SH SYNOPSIS
.P
tibet apropros <terms> [\-\-comments] [\-\-limit=N] [\-\-ignorecase]
.SH DESCRIPTION
.P
Runs the TSH \fB:apropos\fP command to find methods related to one or more topics\.
.P
This is a good command to use when you know what you'd like to do conceptually
but are unsure of what options TIBET may offer to support your goals\.
.P
By default this command searches method names for matches to search terms\.
The terms provided can be simple strings or JavaScript\-style RegExp literals\.
When you provide more than one term the terms are combined using \fBand\fP semantics
meaning that all terms must match a result for it to be presented\. You can use
RegExp literal syntax with vertical bars (|) to create \fBor\fP conditions\.
.P
Output from this command is produced in a format compatible with copy/paste into
a \fBtibet reflect\fP command to explore individual entries more deeply\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fBterms\fP :
A space\-separated list of separate terms to match\. Each term can be either a
simple string or a JavaScript RegExp literal\.
.IP \(bu 2
\fB\-\-comments\fP :
Search comment text in addition to the method name\. This will greatly expand
the set of returned values depending on the term in question\.
.IP \(bu 2
\fB\-\-ignorecase\fP :
Use a case\-insensitive search\. Searches are normally case\-insensitive to
improve the chances you will find appropriate suggestions in the result list\.
You can use \fB\-\-no\-ignorecase\fP as an alternative to using \fBfalse\fP here\.
.IP \(bu 2
\fB\-\-limit\fP :
Set a minimum match count for success\. Items which don't match the search
term at least \fB\-\-limit\fP number of times will be discarded\. The default value is
2\.

.RE
.SH CONFIGURATION SETTINGS
.P
No TIBET configuration variables are utilized by this command\.
.SH ENVIRONMENT VARIABLES
.P
No process environment variables are required by this command\.
.SH EXAMPLES
.SS Search for methods whose name matches a regular expression:
.P
.RS 2
.nf
$ tibet apropos '/nodeGetFirst/'

Loading TIBET via PhantomJS 2\.0\.0 at September 26, 2015 at 11:14:56 MDT
TIBET loaded in 3516 ms\. Starting execution\.

# by name
#
TP\.nodeGetFirstAncestorByAttribute
TP\.nodeGetFirstAncestorByTagName
TP\.nodeGetFirstChildByType
TP\.nodeGetFirstChildContentNode
TP\.nodeGetFirstChildElement
TP\.nodeGetFirstDescendantByType
TP\.nodeGetFirstElementByAttribute
TP\.nodeGetFirstElementByTagName
TP\.nodeGetFirstElementChildByAttribute
TP\.nodeGetFirstElementChildByTagName
TP\.nodeGetFirstSiblingElement
.fi
.RE
.SS Search for methods whose name includes a particular string:
.P
.RS 2
.nf
$ tibet apropos clip

Loading TIBET via PhantomJS 2\.0\.0 at September 26, 2015 at 11:14:56 MDT
TIBET loaded in 3516 ms\. Starting execution\.

# by name
#
TP\.elementSetClipRect
TP\.elementGetClipRect
.fi
.RE
.SS Search with case\-sensitivity:
.P
.RS 2
.nf
$ tibet apropos clip \-\-no\-ignorecase

Loading TIBET via PhantomJS 2\.0\.0 at September 26, 2015 at 11:14:56 MDT
TIBET loaded in 3516 ms\. Starting execution\.

# by name
#
.fi
.RE
.SS Expand the case\-insensitive search to include method comment text:
.P
.RS 2
.nf
$ tibet apropos clip \-\-comments

Loading TIBET via PhantomJS 2\.0\.0 at September 26, 2015 at 11:14:56 MDT
TIBET loaded in 3516 ms\. Starting execution\.

# by name
#
TP\.elementSetClipRect (8)
TP\.elementGetClipRect (7)
#
# by comment
#
.fi
.RE
.SS Expand that search to include method comments and lower match counts:
.P
.RS 2
.nf
$ tibet apropos clip \-\-comments \-\-limit 1

Loading TIBET via PhantomJS 2\.0\.0 at September 26, 2015 at 11:14:56 MDT
TIBET loaded in 3516 ms\. Starting execution\.

# by name
#
TP\.elementSetClipRect (8)
TP\.elementGetClipRect (7)
#
# by comment
#
TP\.gui\.MultiTransition\.Inst\.step (1)
TP\.xctrls\.clipbox\.Inst\.setDisplayValue (1)
TP\.elementWrapToContent (1)
.fi
.RE
.SS Reflect on a resulting method directly:
.P
.RS 2
.nf
$ tibet reflect TP\.elementGetClipRect

# Loading TIBET platform at 2019\-08\-03T17:11:29\.832Z
# TIBET reflection suite loaded and active in 5981ms

TP\.elementGetClipRect

function elementGetClipRect(anElement)

/**
 * @method elementGetClipRect
 * @summary Returns the element's clipping rectangle\.
 * @description The clipping rectangle is assumed to be in pixels (something
 *     like 'rect(10px 10px 10px 10px)')\. If the clipping rectangle is not a
 *     '4 valued' value, null is returned\. Each individual value is
 *     processed and turned from its current value into pixels (i\.e\. the
 *     value might be '4em' \- this is converted into pixels)\. If the value
 *     is 'auto', a null is placed into that position in the Array\.
 * @param {HTMLElement} anElement The element to extract the clipping
 *     rectangle from\.
 * @exception TP\.sig\.InvalidElement
 * @exception TP\.sig\.InvalidStyleDeclaration
 * @returns {Number[]} An Array of Numbers containing the element's clipping
 *     rectangle *expressed in number of pixels*\. The numbers are arranged
 *     in the following order: top, right, bottom, left\.
 */

\|\./public/TIBET\-INF/tibet/src/tibet/kernel/TIBETDHTMLPrimitivesPost\.js
.fi
.RE
.SH TIBET SHELL
.P
This command invokes the client\-side \fB:apropos\fP command, passing all flags and
command line arguments to that command for processing\.
.P
Command invocation is done via the \fBtibet tsh\fP command machinery, which is
inherited by this command\.
.SH TROUBLESHOOTING
.SH SEE ALSO
.RS 0
.IP \(bu 2
tibet\-reflect(1)
.IP \(bu 2
tibet\-tsh(1)

.RE

