.TH "TIBET\-TAG" "1" "September 2020" "" ""
.SH "NAME"
\fBtibet-tag\fR \- creates a new TIBET tag
.SH SYNOPSIS
.P
\fBtibet tag [[\-\-name] [<root>\.][<namespace>(\.|:)]]<tagname>
    [\-\-action | \-\-compiled | \-\-info | \-\-templated]
    [\-\-supertype <typename] [\-\-dir <dirname>] [\-\-dna <template>]
    [\-\-xmlns <nsuri>] [\-\-package <package>] [\-\-config <cfg>]\fP
.SH DESCRIPTION
.P
Creates a new TIBET tag using the supplied tag name and parameters\.
.P
Tag names can supply one, two or three parts, separated by \fB\|\.\fP or \fB:\fP\|\.
.P
If three parts are supplied, they are used as the root namespace,
the tag namespace and the tag name, respectively\.
.P
If two parts are supplied, they are used for the tag namespace and the tag
name and the root namespace is defaulted to either \fBAPP\fP or \fBTP\fP, depending on
whether this command is being executed in an application project or the TIBET
library\.
.P
If one part is supplied, and this command is being executed in an application
project, the tag namespace is defaulted to the application project name and
the root namespace is defaulted as it is when two parts are supplied\. It is not
a valid operation to execute this command with one part when executed inside of
the TIBET library\.
.P
Depending on the DNA chosen the result will be creation of the tag and
optionally a template, style sheet, and test file\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fB\-\-name\fP :
An alternate way to provide the tag name to create\.
.IP \(bu 2
\fB\-\-xmlns\fP :
Lets you define a specific XMLNS URI for any XHTML and CSS references\. The
default will be \fBurn:app:\fP or the standard TIBET prefix URI\.
.IP \(bu 2
\fB\-\-supertype\fP :
The name of the supertype to use for the target tag\. This should be
specified as a fully\-qualified {root}\.{namespace}\.{typename} triplet\.
.IP \(bu 2
\fB\-\-action\fP:
Specify that the new tag should be an action tag and use the appropriate dna
and supertype for a \fBTP\.tag\.ActionTag\fP subtype\.
.IP \(bu 2
\fB\-\-compiled\fP:
Specify that the new tag should be a compiled tag and use the appropriate
dna and supertype for a \fBTP\.tag\.CompiledTag\fP subtype\.
.IP \(bu 2
\fB\-\-info\fP:
Specify that the new tag should be an info tag and use the appropriate
dna and supertype for a \fBTP\.tag\.InfoTag\fP subtype\.
.IP \(bu 2
\fB\-\-templated\fP:
Specify that the new tag should be a templated tag and use the appropriate
dna and supertype for a \fBTP\.tag\.TemplatedTag\fP subtype\. This is the default\.
.IP \(bu 2
\fB\-\-dna\fP :
The name of the dna (essentially a directory reference) to clone and process
to produce the new type\. The default is \fBtemplatedtag\fP\|\. Other tag\-specific
options are \fBactiontag\fP, \fBcomputedtag\fP and \fBinfotag\fP\|\. (As you can see the dna
name is often simply the lowercased name of a type to use as the supertype, but
each does in fact refer to a unique dna directory\.
.IP \(bu 2
\fB\-\-config\fP :
Used as the name of the config package in the cfg package file that the
new type will be made a part of\. If this parameter is not supplied, the default
for a type being created in a project is \fBscripts\fP and for a type being created
in the TIBET library is the same as the type namespace name\.
.IP \(bu 2
\fB\-\-package\fP :
Used to determine the cfg package file that will be updated with entries to
load the new type and configure it\. If this parameter is not supplied, the
default for a type being created in a project is \fB~app_cfg/\.xml\fP\|\. For
a type created in the TIBET library it's \fBlib_cfg/lib_namespaces\.xml\fP\|\.
.IP \(bu 2
\fB\-\-dir\fP :
Used as the destination directory for the newly created source code files
representing the type\. If this parameter is not supplied, the default for a type
being created in a project is \fB~app_tags\fP and for a type being created in
the TIBET library is \fB~lib_src/\fP\|\.

.RE
.SH CONFIGURATION SETTINGS
.RS 0
.IP \(bu 2
\fBtibet\.project\.name\fP:
The 'appname' as represented by the name of the project\.

.RE
.SH ENVIRONMENT VARIABLES
.P
No process environment variables are required by this command\.
.SH EXAMPLES
.SS Create a new tag in the default application namespace
.P
.RS 2
.nf
$ tibet tag header

working in: /Users/ss/temporary/hello/_header_
processing directories\.\.\.
processing templates\.\.\.
templating complete\.\.\.
positioning files\.\.\.
positioning complete\.\.\.
adjusting package entries\.\.\.
<package src="~app_tags/APP\.hello\.header/"/> (added)
New configuration entries created\. Review/Rebuild as needed\.
Cleaning up working directory\.
Type DNA 'templatedtag' cloned to ~app_tags/APP\.hello\.header as 'header'\.
.fi
.RE
.P
Note that the \fBtag\fP command does not define new namespaces so if you use this
approach you should be referring to an existing namespace or you should be
prepared to define the namespace as part of your application startup sequence\.
.P
Also note that TIBET has also updated the package@config so our tag loads:
.P
.RS 2
.nf
<config id="scripts">
    <!\-\- put your source scripts here \-\->
    \.\.\.

    <script src="~app_src/APP\.hello\.Header\.js"/>
</config>
.fi
.RE
.SH TIBET SHELL
.P
This command has no client\-side TSH peer command\.
.SH TROUBLESHOOTING
.SH SEE ALSO
.RS 0
.IP \(bu 2
tibet\-clone(1)
.IP \(bu 2
tibet\-package(1)
.IP \(bu 2
tibet\-type(1)

.RE

