.TH "TIBET\-RELEASE" "1" "January 2016" "" ""
.SH "NAME"
\fBtibet-release\fR \- prep and tag a release of TIBET
.SH SYNOPSIS
.P
.RS 2
.nf
tibet release
.fi
.RE
.SH DESCRIPTION
.P
Performs the steps necessary to tag a release of the TIBET library\.
.P
The release process consists of several steps to sanity check the
.br
current repository followed by a number of steps which work to build
.br
a releasable version, tag it, commit it, and merge/push it to master\.
.P
Before proceeding this command will:
.P
Verify the current branch is develop\.
.br
Verify the branch is not dirty\. [\-\-dirty (dev\-only)]
.br
Verify the branch is up\-to\-date\. [\-\-local]
.P
IFF all the prior checks pass:
.P
Run \fBtibet build_all\fP to build distro\. [\-\-no\-build]
.br
Run the version update template\.
.br
Update TIBET\\'s package\.json file\.
.br
Run \fBtibet checkup\fP to lint/test\. [\-\-no\-check]
.P
IFF all that runs and passes testing it:
.P
Commits the changes which resulted\.
.br
Tags the develop branch with {tag}\-develop\.
.br
Pushes those changes to origin/develop\.
.P
IFF that all worked successfully it:
.P
Checks out the master branch\.
.br
Merges in the develop branch\.
.br
Commits the changes to master\.
.br
Tags the commit with the release tag\.
.br
Pushes the commit and related tag\.
.P
Once that is complete it:
.P
Writes out latest\.js content to be used in the technicalpursuit\.com repo\.
.br
Writes out instructions on the final manual steps to do to publish TIBET\.

