.TH "TIBET\-USER" "1" "March 2020" "" ""
.SH "NAME"
\fBtibet-user\fR \- adds/updates user configuration data
.SH SYNOPSIS
.P
\fBtibet user <username> <password> [\-\-env <env>]
    [\-\-role <role|roles>] [\-\-org <org|orgs>] [\-\-unit unit]\fP
.SH DESCRIPTION
.P
!!! NOTE: this command and the file(s) it manages are NOT SECURE and should
never be used in production\. This command is provided for convenience to let you
simulate users, roles, orgs, and units during development only\. !!!
.P
Manages and/or displays current TIBET user configuration data in the form of a
user file and one or more associated vcards, one per username\.
.P
This command lets you add, or update user data stored in \fB~user_file\fP (usually
\fBusers\.json\fP) such that the resulting data will work properly with default
lightweight authentication logic from the TDS\.
.P
When you add a new user that user will have a vcard generated for them and
stored in \fB~app_dat/{username}_vcard\.xml\fP\|\. If you specify an existing user that
user's vcard is updated with any new data provided\.
.P
A user's vcard is sent to the client by the TDS in response to requests when
that user logs in, providing the client with role, org, and unit data\.
.P
NOTE that if you use this command to set values it will rewrite the user file by
using the beautify npm module to process the stringified JSON content\. As a
result your file may not retain its appearance after updates\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fBusername\fP :
The username to define or verify\.
.IP \(bu 2
\fB\-\-env\fP :
Provides a way to specifically target a particular environment such as
\fBdevelopment\fP within a configuration file\.
.IP \(bu 2
\fB\-\-pass\fP :
Flag to use to set a password for a particular user\.
.IP \(bu 2
\fB\-\-role\fP :
One or more role names, separated by commas\. The resulting set of roles is
injected into the user's associated vcard\.
.IP \(bu 2
\fB\-\-org\fP :
One or more org names, separated by commas\. The resulting set of orgs is
injected into the user's associated vcard\.
.IP \(bu 2
\fB\-\-unit\fP :
A unit name\. If you're using a unit you should supply only a single org\.

.RE
.SH CONFIGURATION SETTINGS
.P
No TIBET configuration variables are utilized by this command\.
.SH ENVIRONMENT VARIABLES
.P
No process environment variables are required by this command\.
.SH EXAMPLES
.SS Check to see if a particular user has been defined
.P
.RS 2
.nf
$ tibet user fluffy

User was found\.
.fi
.RE
.SS Define a new user
.P
.RS 2
.nf
$ tibet user fuzzy \-\-pass tooeasytoguess

User added\.
.fi
.RE
.P
Note that passwords are hashed and encrypted in the \fBusers\.json\fP file so they
are not stored in plain text\.
.P
.RS 2
.nf
$ cat users\.json
{
    "default": {},
    "development": {
        "guest": "a3bc2645acb9cf7051998cb6b7539b79253d67cadb4a1c514e077b882a1b17bc",
        "fluffy": "a468ebdb2000c154dad108949333a588d7545efa86d3beb673349223e43cb9ed",
        "testy": "e9381a7cef0756c6c57c41e80ac491a48b37df21300b0180a635117061c9e9fd"
    }
}
.fi
.RE
.SH TIBET SHELL
.P
This command has no client\-side TSH peer command\.
.SH TROUBLESHOOTING
.SH SEE ALSO

