.TH "TIBET\-LINT" "1" "October 2019" "" ""
.SH "NAME"
\fBtibet-lint\fR \- runs various lint tools on package files
.SH SYNOPSIS
.P
\fBtibet lint [[\-\-filter] <filter>] [\-\-force] [\-\-nodes] [[\-\-style] [\-\-js] [\-\-json] [\-\-xml] [\-\-only]] [\-\-quiet] [\-\-scan] [\-\-stop] [package\-opts] [eslint\-opts] [stylelint\-opts]\fP
.SH DESCRIPTION
.P
Runs a variety of lint tools on files specified in a TIBET package\.
.P
The optional \fBfilter\fP argument provides a string or regular expression
used to filter file names\. If the filter begins and ends with / it is
treated as a regular expression for purposes of file filtering\.
.P
\fB\-\-force\fP overrides any information found in \.tibelint\.json which would otherwise
keep lint from looking at files it thinks haven't changed since the last run\.
This is a flag you should always include in your CI / build configurations\.
.P
\fB\-\-scan\fP overrides any package options and causes the lint command to scan the
filesystem rather than using package configuration entries to determine the file
set to process\.
.P
\fB\-\-stop\fP tells the lint process to stop running after the first error condition,
supporting a fast\-fail approach for build scripts etc\.
.P
\fB\-\-nodes\fP tells the linter to use the package node \fBsrc\fP and/or \fBhref\fP values to
locate files\. This is the default as opposed to \fB\-\-scan\fP which looks at the file
system for raw files by extension\.
.P
The various "extension" flags (\fB\-\-js\fP, \fB\-\-json\fP, \fB\-\-style\fP, \fB\-\-xml\fP) tell lint
whiich file types you want to scan\. By default all are checked\. You can combine
any one of these flags with \fB\-\-only\fP to lint only that type of file\.
.P
\fB[package\-opts]\fP refers to valid options for a TIBET Package object and help
determine which subset of the application's manifests should be targeted\. These
include \fB\-\-package\fP, \fB\-\-config\fP, \fB\-\-phase\fP, \fB\-\-context\fP, etc\. The targeted
package@config defaults to \fB~app_cfg/main\.xml\fP and its default config (usually
\fBbase\fP)\. See help on the \fBtibet package\fP command for more information\.
.P
\fB[eslint\-opts]\fP refers to \fB\-\-esconfig\fP, \fB\-\-esrules\fP, and \fB\-\-esignore\fP which
let you configure \fBeslint\fP to meet your specific needs\. The linter will
automatically take advantage of a \fB\|\.eslintrc\fP file in your project\.
.P
\fB[stylelint\-opts]\fP refers to \fB\-\-styleconfig\fP which allows you to specify a
\fB\|\.stylelintrc\fP file whose content should be used\. The lint command relies on
\fB\|\.stylelintrc\fP as used by the styleline command (installed separately)\. The
default file is the one in your project\.
.P
All of the linters can be disabled individually by using a \fB\-\-no\-\fP prefix\.
For example: \fB\-\-no\-style \-\-no\-js \-\-no\-json \-\-no\-xml\fP will turn off all
the currently supported linters\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fB\-\-force\fP:
Tell the linter to ignore any \fBtibetlint\.json\fP file content which would
limit the check to only changed files\. With \fB\-\-force\fP set all files will be
checked even if they haven't changed since the last lint pass\.
.IP \(bu 2
\fB\-\-nodes\fP :
Tell the linter not to scan but instead to use the nodes from the
package@config and use their \fBsrc\fP or \fBhref\fP values to determine the list of
files to be checked\.
.IP \(bu 2
\fB\-\-only\fP :
Tell the linter to only check the specific file types provided by one of the
other flags such as \fB\-\-js\fP, \fB\-\-json\fP, \fB\-\-style\fP, or \fB\-\-xml\fP\|\.
.IP \(bu 2
\fB\-\-quiet\fP :
Tells the linter to suppress detailed warnings if possible\.
.IP \(bu 2
\fB\-\-scan\fP :
Tells the linter to scan the directory tree and ignore any package@config
specification\. Without this flag only files found in the project package files
will be linted, making it easy to lint only those files your project actually
makes direct use of\.
.IP \(bu 2
\fB\-\-stop\fP :
Tells the linter to stop after the first file with errors\.

.RE
.SH CONFIGURATION SETTINGS
.RS 0
.IP \(bu 2
\fBboot\.deafult_package\fP:
Read if no other default package information is available\.
.IP \(bu 2
\fBcli\.lint\.js_extensions\fP:
The list of extensions used to scan for JavaScript source files\.
.IP \(bu 2
\fBcli\.lint\.style_extensions\fP:
The list of style sheet extensions used to scan for style information\.
.IP \(bu 2
\fBcli\.lint\.xml_extensions\fP:
The list of XML file extensions to scan when looking for XML files\.

.RE
.SH ENVIRONMENT VARIABLES
.P
No process environment variables are required by this command\.
.SH FILES
.RS 0
.IP \(bu 2
\fBtibetlint\.json\fP:
A file containing information on the last lint run\. This file is used when
the \fB\-\-force\fP flag is not set to determine timestamp and/or list of files to be
checked:
{
.P
.RS 2
.nf
"linty": 1,
"errors": 0,
"warnings": 1,
"checked": 13,
"unchanged": 0,
"filtered": 1,
"files": 14,
"recheck": ["/Users/ss/temporary/hello/public/src/tags/APP\.hello\.app/APP\.hello\.app\.js"],
"lastrun": 1564939681906
.fi
.RE
}

.RE
.SH EXAMPLES
.SS Lint all package\-referenced files in an application
.P
.RS 2
.nf
$ tibet lint

0 errors, 0 warnings in 14 of 14 files\.
.fi
.RE
.SS Lint all files in an application directory tree
.P
.RS 2
.nf
$ tibet lint \-\-scan

0 errors, 0 warnings in 97 of 97 files\.
.fi
.RE
.SS Lint a specific file, package\-mentioned or otherwise
.P
.RS 2
.nf
$ tibet lint \-\-scan \-\-filter /makefile/

/Users/ss/temporary/todomvc/public/TIBET\-INF/cmd/makefile\.js
  106:13   warn    'dir' is defined but never used                                no\-unused\-vars
  112:27   error   Unexpected trailing comma\.                                     comma\-dangle
1 errors, 1 warnings in 1 of 1 files\.
.fi
.RE
.SH TIBET SHELL
.P
This command has no client\-side TSH peer command\.
.SH TROUBLESHOOTING
.SH SEE ALSO
.RS 0
.IP \(bu 2
tibet\-doclint(1)

.RE

