.TH "TIBET\-MAKE" "1" "August 2018" "" ""
.SH "NAME"
\fBtibet-make\fR \- runs a TIBET makefile\.js target
.SH SYNOPSIS
.P
tibet make <target> [\-\-list]
.SH DESCRIPTION
.P
Runs a target function in a TIBET \fBmakefile\.js\fP file via a JS Promise\.
.P
This command supports lightweight commands in the form of functions, much
like Grunt or Gulp\. There's no dependency checking or true 'make'\-like
functionality but \fBmakefile\.js\fP code does leverage JavaScript Promises to
coordinate tasks and their interactions, particularly when calling tasks
within tasks and when dealing with asynchronous tasks\.
.P
TIBET provides a default \fBmakefile\.js\fP which supports basic operations such as
clean, build, and rollup that are common in TIBET applications\. By providing
these commands as make targets it is easy for you to modify them to meet your
specific project requirements\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fB\-\-list\fP :
Used to list the available \fBmakefile\.js\fP targets you can run\.
.IP \(bu 2
\fB\-\-timeout <ms>\fP :
Gives you a way to provide a millisecond timeout value in which each task
must complete successfully\. The default is 15 seconds (15000)\.

.RE
.SH EXAMPLES
.SS List available makefile\.js targets
.P
.RS 2
.nf
$ tibet make \-\-list

Available targets:

    build checkup clean deploy resources rollup
.fi
.RE
.SS Run a make target explicitly
.P
.RS 2
.nf
$ tibet make clean

cleaning\.\.\.
Task complete: 7ms\.
.fi
.RE
.SS Run a make target implicitly
.P
.RS 2
.nf
$ tibet clean

Delegating to 'tibet make clean'
cleaning\.\.\.
Task complete: 4ms\.
.fi
.RE

