.TH "TIBET\-HELP" "1" "April 2019" "" ""
.SH "NAME"
\fBtibet-help\fR \- displays help specific to TIBET
.SH SYNOPSIS
.P
tibet help <topic>
.SH DESCRIPTION
.P
Displays help for a specific command or the 'tibet' command\.
.P
You can alternatively get usage data via the \fB\-\-usage\fP flag on each command
or complete help output by using the \fB\-\-help\fP flag on the target command\.
.SH EXAMPLES
.SS List help on the \fBtibet\fP command itself
.P
.RS 2
.nf
$ tibet

Usage: tibet <command> <options>

The tibet command can invoke TIBET built\-ins, custom commands,
tibet makefile\.js targets, grunt targets, or gulp targets based
on your project configuration and your specific customizations\.

<command> built\-ins include:

    appcache apropos clone config context deploy doclint
    echo freeze help init lint make package quickstart
    reflect release resources rollup start tag test thaw
    tsh user version

makefile\.js targets include:

    build checkup clean deploy resources rollup

<options> always include:

    \-\-help         display command help text
    \-\-usage        display command usage summary
    \-\-color        colorize the log output [true]
    \-\-verbose      work with verbose output [false]
    \-\-debug        turn on debugging output [false]
    \-\-stack        display stack with error [false]

Configure default parameters via 'tibet config'\.

hello@0\.1\.0 /Users/ss/\.nvm/v0\.10\.36/bin/tibet
.fi
.RE

