.TH "TIBET\-USER" "1" "March 2017" "" ""
.SH "NAME"
\fBtibet-user\fR \- adds/updates user configuration data
.SH SYNOPSIS
.P
tibet user <username> <password>
.SH DESCRIPTION
.P
Manages and/or displays current TIBET user configuration data\.
.P
The TIBET Data Server (TDS) uses a simple default authentication model
.br
which relies on usernames and hashed passwords stored in the tds\.json
.br
file loaded by the server when it starts\. While this is clearly not a
.br
production\-capable approach it does allow you to experiment with logins\.
.P
This command lets you list, add, or update user data stored in tds\.json
.br
such that the resulting data will work properly with default authenticate
.br
logic from the TDS plugin catalog\.
.P
NOTE that if you use this command to set values it will rewrite tds\.json
.br
by using the beautify npm module to process the stringified JSON content\.
.br
As a result your file may not retain its appearance after updates\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fBusername\fP :
.br
The username to define or verify\.
.IP \(bu 2
\fB\-\-env\fP :
.br
Provides a way to specifically target a particular environment such as
.br
\fBdevelopment\fP within a configuration file\.
.IP \(bu 2
\fB\-\-pass\fP :
.br
Flag to use to set a password for a particular user\.

.RE
.SH EXAMPLES
.SS Check to see if a particular user has been defined
.P
.RS 2
.nf
$ tibet user fluffy

User was found\.
.fi
.RE
.SS Define a new user
.P
.RS 2
.nf
$ tibet user fuzzy \-\-pass tooeasytoguess

User added\.
.fi
.RE
.P
Note that passwords are hashed in the \fBtds\.json\fP file so they are not stored in
.br
plain text\.
.P
.RS 2
.nf
$ cat tds\.json

{
    "cli": {
        "color": {
            "debug": "green"
        }
    },
    "use": {
        "proxy": true,
        "tasks": true,
        "watch": true
    },
    "users": {
        "fluffy": "42d388f8b1db997faaf7dab487f11290",
        "fuzzy": "31234aa2aeadb4b73008a97c4f7d43b7"
    }
}
.fi
.RE
.SH SEE ALSO

