.TH "TIBET\-CONTEXT" "1" "April 2019" "" ""
.SH "NAME"
\fBtibet-context\fR \- outputs current context information to stdout
.SH SYNOPSIS
.P
tibet context
.SH DESCRIPTION
.P
Displays core contextual information about the current project including values
for the library root, application root, current project name, etc\. The data
provided is often helpful in showing you where the key paths for project launch
point and what the baseline boot profile elements are\.
.SH EXAMPLES
.SS In a TIBET project
.P
.RS 2
.nf
$ tibet context

{
    "name": "d2d",
    "version": "0\.1\.0",
    "in_library": false,
    "in_project": true,
    "~": "~/tmp/d2d",
    "~app": "~/public",
    "~lib": "~app/TIBET\-INF/tibet",
    "boot": {
        "package": "~app_cfg/main\.xml",
        "configs": ["base", "contributor", "developer", "full", "test"]
    }
}
.fi
.RE
.SS In the TIBET library
.P
.RS 2
.nf
$ tibet context

{
    "name": "tibet",
    "version": "v5\.0\.0\-dev\.7",
    "in_library": true,
    "in_project": false,
    "~": "~/dev/TPI/TIBET",
    "~app": "~/dev/TPI/TIBET",
    "~lib": "~/dev/TPI/TIBET",
    "boot": {
        "package": "~lib_cfg/TIBET\.xml",
        "configs": ["base", "developer", "full", "test"]
    }
}
.fi
.RE
.SH SEE ALSO
.RS 0
.IP \(bu 2
tibet\-config(1)

.RE

