.TH "TIBET\-DOCLINT" "1" "June 2020" "" ""
.SH "NAME"
\fBtibet-doclint\fR \- validates method comment content
.SH SYNOPSIS
.P
\fBtibet doclint [<target>] [\-\-filter <filter>] [\-\-missing] [\-\-tap] [\-\-context <app|lib|all>]\fP
.SH DESCRIPTION
.P
Runs the TSH \fB:doclint\fP command to validate method comment content\.
.P
The doclint command uses TIBET reflection to find all methods in your
application that match an optional \fB<target>\fP and/or \fB\-\-filter\fP\|\. Matched methods
then have their comment text checked for conformance to JSDoc3 and TIBET comment
standards\. This check can be a part of an overall quality pass which includes
running \fBtibet lint\fP and \fBtibet test\fP on your code\.
.P
If you provide an optional string parameter it will be used as a target ID which
must resolve via TP\.bySystemId\. Only methods owned by that target will be
checked\.
.P
If you provide a \-\-filter the method names themselves will be filtered to match
only the pattern or string provided\.
.P
If you specify \fB\-\-missing\fP only missing comments will be reported\. No additional
checks on content will be performed\.
.P
The context (app, lib, or all) is generally defaulted based on any target data
given\. For example, using a target of \fBAPP\.*\fP will cause an \fBapp\fP context while
using a target of \fBTP\.*\fP will default to a lib context\. To use the \fBall\fP context
you must specify it explicitly\.
.P
By default output from this command follows the 'TAP' format\. You can turn that
off using \fB\-\-tap=false\fP or \fB\-\-no\-tap\fP\|\.
.P
Note that because it uses method reflection, not file lists, to drive the checks
when this command outputs file counts they represent the number of unique files
containing matching methods, not a full list of project files\. This can be
disconcerting at first if you are used to listings which are built by
file\-driven tools\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fBtarget\fP :
An optional target, usually a type name, to check\.
.IP \(bu 2
\fB\-\-context\fP :
Sets the context of the method scan which is run\. The default is \fBapp\fP
which scans only application\-level resources, ignoring any potential library
resources\. Other values are \fBlib\fP and \fBall\fP\|\.
.IP \(bu 2
\fB\-\-filter\fP :
An optional regular expression, expressed in /foo/ig form\. This filter will
be applied to fully\-qualified method names\.
.IP \(bu 2
\fB\-\-missing\fP :
Optional flag which restricts lint warnings/errors to just missing comments\.
.IP \(bu 2
\fB\-\-tap\fP :
Optional flag to turn on/off TAP formatted output\. The default is true\.

.RE
.SH CONFIGURATION SETTINGS
.P
No TIBET configuration variables are utilized by this command\.
.SH ENVIRONMENT VARIABLES
.P
No process environment variables are required by this command\.
.SH EXAMPLES
.SS Checking a specific type for documentation lint
.P
Assume a brand\-new project\. The application type won't have any methods yet
so an initial test won't find any methods and hence will list no files:
.P
.RS 2
.nf
$ tibet doclint APP\.hello\.Application

# Loading TIBET platform at 2019\-11\-09T17:43:17\.668Z
# TIBET reflection suite loaded and active in 5219ms
# PASS: 0 errors in 0 of 0 files\.
# Finished in 3710 ms w/TSH exec time of 77 ms\.
.fi
.RE
.P
If we add a method but fail to add a proper comment we see different output:
.P
.RS 2
.nf
# Loading TIBET platform at 2019\-11\-09T17:43:17\.668Z
# TIBET reflection suite loaded and active in 5219ms
not ok \- ~app_src/APP\.test1\.Application\.js
# APP\.test1\.Application\.TypeLocal\.test (1) \-> [missing comment]
# FAIL: 1 errors in 1 of 1 files\.
# Finished in 3985 ms w/TSH exec time of 75 ms\.
.fi
.RE
.P
If we then comment our new method we'll see output to that effect:
.P
.RS 2
.nf
# Loading TIBET platform at 2019\-11\-09T17:43:17\.668Z
# TIBET reflection suite loaded and active in 5219ms
ok \- ~app_src/APP\.test1\.Application\.js
# PASS: 0 errors in 0 of 1 files\.

# Finished in 3698 ms w/TSH exec time of 76 ms\.
.fi
.RE
.SS Checking your entire application for documentation lint
.P
.RS 2
.nf
$ tibet doclint

# Loading TIBET platform at 2019\-11\-09T17:43:17\.668Z
# TIBET reflection suite loaded and active in 5219ms
ok \- ~app_src/APP\.test1\.Application\.js
ok \- ~app_tags/APP\.test1\.app/APP\.test1\.app\.js
# PASS: 0 errors in 0 of 2 files\.
# Finished in 10097 ms w/TSH exec time of 6299 ms\.
.fi
.RE
.SS Checking a specific filtered set of targets for doclint
.P
.RS 2
.nf
$ tibet doclint \-\-filter /app/

# Loading TIBET platform at 2019\-11\-09T17:43:17\.668Z
# TIBET reflection suite loaded and active in 5219ms
ok \- ~app_tags/APP\.test1\.app/APP\.test1\.app\.js
# PASS: 0 errors in 0 of 1 files\.
# Finished in 10435 ms w/TSH exec time of 6723 ms\.
.fi
.RE
.P
Note that you can also do case\-insensitive filtering (with \fBi\fP) as follows:
.P
.RS 2
.nf
$ tibet doclint \-\-filter /app/i

# Loading TIBET platform at 2019\-11\-09T17:43:17\.668Z
# TIBET reflection suite loaded and active in 5219ms
ok \- ~app_src/APP\.test1\.Application\.js
ok \- ~app_tags/APP\.test1\.app/APP\.test1\.app\.js
# PASS: 0 errors in 0 of 2 files\.
# Finished in 10556 ms w/TSH exec time of 6344 ms\.
.fi
.RE
.SH TIBET SHELL
.P
This command invokes the client\-side \fB:doclint\fP command, passing all flags and
command line arguments to that command for processing\.
.P
Command invocation is done via the \fBtibet tsh\fP command machinery, which is
inherited by this command\.
.SH TROUBLESHOOTING
.SH SEE ALSO
.RS 0
.IP \(bu 2
tibet\-lint(1)

.RE

