.TH "TIBET\-LINT" "1" "January 2016" "" ""
.SH "NAME"
\fBtibet-lint\fR \- runs various lint tools on package files
.SH SYNOPSIS
.P
.RS 2
.nf
tibet lint [[\-\-filter] <filter>] [\-\-scan] [\-\-stop] [package\-opts] [eslint\-opts] [csslint\-opts]
.fi
.RE
.SH DESCRIPTION
.P
Runs a variety of lint tools on files specified in a TIBET package\.
.P
The optional \fBfilter\fP argument provides a string or regular expression
.br
used to filter file names\. If the filter begins and ends with / it is
.br
treated as a regular expression for purposes of file filtering\.
.P
[package\-opts] refers to valid options for a TIBET Package object\.
.br
These include \-\-package, \-\-config, \-\-phase, \-\-assets, etc\.
.br
The package#config defaults to \fB~app_cfg/app\.xml\fP and its default
.br
config (usually #base) so your typical configuration is linted\.
.br
See help on the \fBtibet package\fP command for more information\.
.P
[eslint\-opts] refers to \-\-esconfig, \-\-esrules, and \-\-esignore which
.br
let you configure eslint to meet your specific needs\. The linter will
.br
automatically take advantage of a \fB\|\.eslintrc\fP file in your project\.
.P
[csslint\-opts] refers to \-\-cssconfig which allows you to specify a
.br
\fB\|\.csslintrc\fP file whose content should be used\. The lint command
.br
relies on \fB\|\.csslintrc\fP as used by the csslint command line\. The default
.br
file is the one in your project, followed by the TIBET library version\.
.P
All of the linters can be disabled individually by using a \fB\-\-no\-\fP prefix\.
.br
For example: \-\-no\-csslint \-\-no\-eslint \-\-no\-jsonlint \-\-no\-xmllint will turn
.br
off all the currently supported linters\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fB\-\-scan\fP :
.br
Tells the linter to scan the directory tree and ignore any package#config
.br
specification\. Without this flag only files found in the project package files
.br
will be linted, making it easy to lint only those files your project actually
.br
makes direct use of\.
.IP \(bu 2
\fB\-\-quiet\fP :
.br
Tells the linter to suppress warnings if possible\.
.IP \(bu 2
\fB\-\-stop\fP :
.br
Tells the linter to stop after the first file with errors\.

.RE
.SH SEE ALSO
.RS 0
.IP \(bu 2
doclint(1)
.IP \(bu 2
package(1)

.RE

