.TH "TIBET\-VERSION" "1" "December 2015" "" ""
.SH "NAME"
\fBtibet-version\fR \- displays the current project and TIBET version
.SH SYNOPSIS
.P
.RS 2
.nf
tibet version [\-\-check]
.fi
.RE
.SH SYNOPSIS
.P
Displays the current version of TIBET\. Also available as the
.br
\-\-version flag on the 'tibet' command (tibet \-\-version)\.
.P
Use \-\-check to request this command to check whether a newer
.br
version of TIBET has been published\.

