.TH "TIBET\-CLONE" "1" "July 2019" "" ""
.SH "NAME"
\fBtibet-clone\fR \- clones a project from a template directory
.SH SYNOPSIS
.P
tibet clone <target> [\-\-list] [\-\-force] [\-\-name <appname>] [\-\-dna <template>]
.SH DESCRIPTION
.P
Clones a template directory, considered the \fBdna\fP, to create a new project\.
.P
\fB<target>\fP is required and must be a valid directory name to clone to\.
.P
By default the target will be the new project's appname unless otherwise
specified\. You can use \fB\|\.\fP to clone to the current directory HOWEVER no checks
are currently done to prevent potential data loss\. Be careful!
.P
NOTE this command is currently being re\-evaluated and will likely become a
front\-end for Yeoman functionality in a future release\.
.P
Once a project template has been cloned you use the \fBtibet init\fP command to
initialize the project by triggering installation of all project dependencies\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fB\-\-list\fP :
Output a list of available dna options\. No project is created if you use
this option\.
.IP \(bu 2
\fB\-\-force\fP :
Required if you use \fB\|\.\fP as a simple reminder to be careful\. You can also
use \fB\-\-force\fP with existing directories but \fIno checks are done\fR to avoid
overwriting existing files\.
.IP \(bu 2
\fB\-\-name\fP :
Lets you rename from the directory name to an alternative name\. This lets
the directory and appname vary\. This is common when cloning to existing
directories or poorly named ones like those required for GitHub Pages
repositories\.
.IP \(bu 2
\fB\-\-dna\fP :
Lets you clone any valid template in TIBET's \fBdna\fP directory or a
directory of your choosing\. This latter option lets you create your own reusable
custom application templates\.

.RE
.SH EXAMPLES
.SS See the list of available project dna
.P
.RS 2
.nf
$ tibet clone \-\-list

couch
default
electron
ghpages
noserver
.fi
.RE
.SS Create a new project with \fBdefault\fP dna
.P
.RS 2
.nf
$ tibet clone helloworld

TIBET dna 'default' cloned to helloworld as app 'helloworld'\.
.fi
.RE
.SS Create a new project with \fBcouch\fP dna
.P
.RS 2
.nf
$ tibet clone hellocouch \-\-dna couch

TIBET dna 'couch' cloned to hellocouch as app 'hellocouch'\.
.fi
.RE
.SS Create a new project in an existing directory
.P
.RS 2
.nf
$ tibet clone \.

TIBET dna 'default' cloned to \. as app 'hellolocal'
.fi
.RE
.SS Create a named project in an existing directory (empty)
.P
.RS 2
.nf
$ tibet clone \-\-name hello \.

TIBET dna 'default' cloned to \. as app 'hello'\.
.fi
.RE
.SS Create a named project in an existing directory (not empty)
.P
NOTE NOTE NOTE!!! This command can overlay files and is potentially
destructive!!! Future versions of the \fBclone\fP command may use \fByeoman\fP to help
avoid file conflicts, allowing this operation to be done safely\.
.P
.RS 2
.nf
$ tibet clone \-\-name hello \. \-\-force

TIBET dna 'default' cloned to \. as app 'hello'\.
.fi
.RE
.SH SEE ALSO
.RS 0
.IP \(bu 2
tibet\-init(1)

.RE

