.TH "TIBET\-THAW" "1" "April 2020" "" ""
.SH "NAME"
\fBtibet-thaw\fR \- thaws a frozen project's TIBET library reference
.SH SYNOPSIS
.P
\fBtibet thaw [\-\-force]\fP
.SH DESCRIPTION
.P
NOTE: this command will be removed in a future release once splitting
of the TIBET npm package into \fBtibet\-cli\fP and \fBtibet\fP is complete\.
.P
Thaws (un\-freezes) the current application's TIBET library in \fB~app_inf\fP\|\.
.P
By default \fB~app_inf\fP refers to \fBpublic/TIBET\-INF\fP, the default location for
package data, custom commands, etc\. TIBET is configured to allow a version of
TIBET to be frozen into \fB~app_inf/tibet\fP rather than in \fBnode_modules/tibet\fP to
support deployments where the use of the \fBnode_modules\fP directory would be
unnecessary or excessive\.
.P
The thaw command removes any \fB~app_inf/tibet\fP content and returns the
setting for \fBlib_root\fP to its default value of \fB~/node_modules/tibet\fP where the
\fB~\fP in this case represents your project's root directory\.
.P
Since it is inherently destructive this command requires \fB\-\-force\fP to
actually run\.
.SH OPTIONS
.RS 0
.IP \(bu 2
\fB\-\-force\fP :
Required to actually cause a thaw operation to be performed\.

.RE
.SH CONFIGURATION SETTINGS
.P
No TIBET configuration variables are utilized by this command\.
.SH ENVIRONMENT VARIABLES
.P
No process environment variables are required by this command\.
.SH EXAMPLES
.SS Thaw a previously frozen project (\.\.\.but not really\.\.\.)
.P
.RS 2
.nf
$ tibet thaw

Use \-\-force to confirm destruction of ~app_inf/tibet\.
.fi
.RE
.SS Thaw a previously frozen project (\.\.\.and really do it\.\.\.)
.P
.RS 2
.nf
$ tibet thaw \-\-force

updating embedded lib_root references\.\.\.
updating project lib_root setting\.\.\.
Application thawed\. TIBET now boots from ~/node_modules/tibet\.
.fi
.RE
.SH TIBET SHELL
.P
This command has no client\-side TSH peer command\.
.SH TROUBLESHOOTING
.SH SEE ALSO
.RS 0
.IP \(bu 2
tibet\-freeze(1)

.RE

